#!/bin/bash

# Path to hooks
hooks_path="/share/projects/live-repos/git-hooks/hooks"

# Get infos from stdin
read oldrev newrev refname

# Colors for nice output
Normal='\e[0m'
Green='\e[0;32m'
Yellow='\e[0;33m'
Red='\e[0;31m'

ORIGINAL_IFS=$IFS
STATUS=true

affected_files()
{
    for extension in ${@}
    do
        for comitted_file in $( git diff-tree -r ${oldrev}..${newrev} | awk {'print substr($0, index($0,$6))'} )
        do
            if [ "${comitted_file##*.}" = "$extension" ]
            then
                echo "$comitted_file"
            fi
        done
    done
}

commited_file()
{
    sourcefile="${1}"
    git show ${newrev}:"${sourcefile}"
}

# load local dot hooks (e.g. local update.gitolite)
for local_hook in $( ls hooks/$( basename ${0} ).* 2> /dev/null )
do
    ${local_hook} "${oldrev}" "${newrev}" "${refname}"
    if [ $? != 0 ]
    then
        STATUS=false
    fi
done

# load available custom hooks
for custom_hook in $( ls "${hooks_path}/"$( basename ${0} ).* 2> /dev/null )
do
    . "${custom_hook}"
    if [ $? != 0 ]
    then
        STATUS=false
    fi
done

${STATUS}

