#!/bin/bash

warnings=0
found=false

ORIGINAL_IFS=$IFS
IFS=$'\n'
for sourcefile in $( git diff-tree -r ${oldrev}..${newrev} | awk {'print substr($0, index($0,$6))'} )
do
    for extension in "php" "phtml" "php3" "php4" "php5"
    do
        if [ "${sourcefile##*.}" = "$extension" ]
        then
            if [ "$found" = "false" ]
            then
                echo -e "\nPHP Syntax Tests:" >&2
                found=true
            fi
            echo -n "${sourcefile}"
            if ( git show ${newrev}:"${sourcefile}" 2>/dev/null >&2 ) && \
               ! ( git show ${newrev}:"${sourcefile}" | php -l 2>/dev/null >&2 ) 
            then
                echo -e "\t\t${Red}Failed${Normal}"
                warnings=$(( $warnings + 1 ))
                echo >&2
                echo $( git show ${newrev}:"${sourcefile}" | php -l) "${sourcefile}" >&2 
            else
                echo -e "\t\t${Green}Successful${Normal}"
            fi
        fi
    done
done
IFS=$ORIGINAL_IFS

if [ "$found" = "true" ]
then
    if [ $warnings -eq 0 ]
    then
        echo -e "${Green}Everything OK${Normal}\n"
    else
        echo >&2
        echo -e "${Red}$warnings PHP files with possible broken syntax found in this commit${Normal}\n" >&2
        if [ "$blockInvalidPHPSyntax" = "true" ]
        then
            echo -e "${Red}PULL REJECTED${Normal}" >&2
            exit 1
        fi
    fi
fi

