#!/bin/bash

validation=$(git config --bool hook.validation | sed 's|,| |g' | sed 's|[ ]\+| |g')

for entry in validation
do
    extension=$( echo ${entry} | cut -f'1' -d'@')
    module=$( echo ${entry} | cut -f'2' -d'@')
    
    case "${extension}" in
        
        php|php3|php4|php5|phtml)
            error "No validation module for filetype: ${extension}"
          ;;
        
        xml)
            error "No validation module for filetype: ${extension}"
          ;;

        *)
            error "No validation module for filetype: ${extension}"
          ;;
    esac

done

