#!/bin/bash

oldrev="$1"
newrev="$2"
ref="$3"

for sourcefile in `git diff-tree -r ${oldrev}..${newrev} | awk '{print $6}'`
do
    echo "Updated file: ${sourcefile} with extension ${sourcefile##*.}"
done

