#!/bin/bash

warnings=0
found=false

ORIGINAL_IFS=$IFS
IFS=$'\n'
for sourcefile in $( git diff-tree -r ${oldrev}..${newrev} | awk {'print substr($0, index($0,$6))'} )
do
    for extension in "xml"
    do
        if [ "${sourcefile##*.}" = "$extension" ]
        then
            if [ "$found" = "false" ]
            then
                echo -e "\nXML Validation:" >&2
                found=true
            fi
            if ( git show ${newrev}:"${sourcefile}" 2>/dev/null >&2 ) && \
               ! ( git show ${newrev}:"${sourcefile}" | xmllint - 2>/dev/null >&2 ) 
            then
                warnings=$(( $warnings + 1 ))
                echo >&2
                echo "${Red}Invalid xml in ${sourcefile}${Normal}"
                git show ${newrev}:"${sourcefile}" | xmllint - >&2
            fi
        fi
    done
done
IFS=$ORIGINAL_IFS

if [ "$found" = "true" ]
then
    if [ $warnings -eq 0 ]
    then
        echo -e "${Green}Everything OK${Normal}\n"
    else
        echo >&2
        echo -e "${Red}$warnings files with possible invalid XML${Normal}\n" >&2
        if [ "$blockInvalidXML" = "true" ]
        then
            echo -e "${Red}PULL REJECTED${Normal}" >&2
            exit 1
        fi
    fi
fi

